config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do


  devise_for :user, :controllers => {:sessions => "sessions"}
  devise_scope :user do
    match 'choose-school' => 'sessions#choose_school', via: [:get, :post]
    get 'sign-in' => 'sessions#who_are_you', as: :who_are_you
    get 'sign-in-teachers' => 'sessions#new', user: {teacher: true}
    post 'sign-in-teachers' => 'sessions#create'
    get 'sign-in-pupils' => 'sessions#new', user: {pupil: true}
    post 'sign-in-pupils' => 'sessions#create'
    get 'sign-out' => 'sessions#destroy'
  end

  resources :enquiries, only: [:new, :create] do
    collection { get :thanks }
  end

  resources :messages

  #regular routes
  resources :pages, only: :show do
    collection do
      get :product
      get :research
      get :blogs
      get :sample_missions
    end
  end

  get    'presentation/:presentation_id',               to: 'presentations#show', as: 'presentation'
  get    'presentation/:presentation_id/:slide_number', to: 'presentations#show', as: 'presentation_slide'

  get    ':course_id/presentation/:presentation_id', to: 'presentations#show', as: 'course_presentation'
  get    ':course_id/presentation/:presentation_id/:slide_number', to: 'presentations#show', as: 'course_presentation_slide'
  get    'presentation/:slide_id', to: 'presentations#slide_path', as: 'slide'

  draw :faculty

  namespace :pupil, path: 'ppl' do
    resources :lessons, only: [:index, :show] do
      member do
        get '/big_preview', to: 'lessons#big_preview'
        get '/quiz-start', to: 'quizzes#start_quiz', as: :start_quiz
        get '/question', to: 'quizzes#question', as: :question
        post '/question', to: 'quizzes#submit_answer', as: :submit_answer
      end
    end
    resources :results, only: [:index, :show]
    resources :achievements, path: 'my-achievements', only: [:index] do
      get '/set_avatar', action: :set_avatar, on: :member
    end
    get '/my-class', to: 'pupil#my_class'
    get '/my-library', to: 'lessons#library'
    get '/charts/:chart_type', to: 'pupil#charts'
    root 'pupil#home'
  end

  draw :admin
  draw :api

  root 'pages#home'

end

app/models/user/pupil.rb
class User::Pupil < User
  # devise :database_authenticatable, :authentication_keys => [:pupil_identifier]

  attr_accessor :klass

  default_scope -> { order name: :asc}

  belongs_to :school
  has_paper_trail

  has_many :enrollments

  has_many :klasses, through: :enrollments
  has_many :courses, through: :klasses
  has_many :lessons, ->{ selected }, through: :courses

  has_many :lesson_results

  has_many :pupil_avatars
  has_many :avatars, through: :pupil_avatars
  belongs_to :avatar, foreign_key: 'pupil_avatar_id'

  validates :name, presence: true
  validates :school_id, presence: true
  validates :pupil_identifier, presence: true, uniqueness: { scope: :school_id }

  before_validation :assign_pupil_identifier

  enum gender: [:male, :female, :other]

  def password_required?
    false
  end

  def email_required?
    false
  end


  def avatar_image
    avatar&.image || 'locked_avatar'
  end

  def enroll_in klass
    enrollments.create(klass_id: klass.id) unless in?(klass)
  end

  def leave klass
    enrollments.find_by(klass_id: klass.id)&.destroy
  end

  def in? klass
    klasses.include? klass
  end

  def has? avatar
    avatars.find_by(id: avatar.id)
  end


  def performance_graph
    lesson_results.map do |lesson_result|
      [lesson_result.lesson&.lesson_number, lesson_result.score, lesson_result.normalized_in_class_mark, lesson_result.total]
    end
  end

  def average_in_class_mark
    marks = lesson_results.collect &:normalized_in_class_mark
    marks.select! &:present?
    if marks.length > 0
      marks.sum / marks.length
    end
  end

  def average_quiz_mark
    marks = lesson_results.collect &:score
    marks.select! &:present?
    if marks.length > 0
      marks.sum / marks.length
    end
  end
  def average_total
    marks = lesson_results.collect &:total
    marks.select! &:present?
    if marks.length > 0
      marks.sum / marks.length
    end
  end
  

  def lesson_mark lesson
    if lesson = lesson_results.find_by(lesson_id: lesson.id)
      lesson.in_class_mark
    end
  end

  def lesson_comment lesson
    if lesson = lesson_results.find_by(lesson_id: lesson.id)
      lesson.teacher_comments
    end
  end

  def absent lesson
    if lesson = lesson_results.find_by(lesson_id: lesson.id)
      lesson.absent
    end
  end


  def self.import_csv school, file
    require 'csv'
    ActiveRecord::Base.transaction do
      CSV.foreach(file.path, headers: true) do |row|
        school.pupils.create!(
            name: row['Name'],
            email: (row['Email'] || ''),
            age: row['Age'],
            dob: row['Date of Birth'],
            study_year_id: row['Year'],
            gender: row['Gender'],
            specified_class: row['Class'],
            pupil_identifier: row['Pupil ID'],
        )
      end
    end
  end


  belongs_to :q_fun_quiz_attempt, class_name: 'Quiz::Attempt', foreign_key: :fun_quiz_attempt_id
  def fun_quiz_attempt lesson
    unless q_fun_quiz_attempt && fun_quiz_lesson_id == lesson.id
      a = build_q_fun_quiz_attempt 
      a.fun_questions_for lesson
      update(fun_quiz_lesson_id: lesson.id)
      a.save!
    end
    q_fun_quiz_attempt
  end




  private

    def assign_pupil_identifier
      loop do
        num = rand(1..999999)
        @identifier = num.to_s.rjust(6, '0')
        break unless school.pupils.find_by(pupil_identifier: @identifier)
      end
      self.pupil_identifier = @identifier if self.pupil_identifier.blank?
    end

    def assign_pupil_email
      self.email = "#{pupil_identifier}-pupil@#{school.subdomain}.school" if self.email.blank?
    end

end

app/controllers/admin/pupils_controller.rb
class Admin::PupilsController < AdminController
  before_action :set_cupil, only: [:edit, :update]

  def new
    @pupil = User::Pupil.administrators.new
  end

  def edit
  end

  def create
    @pupil = User::Pupil.administrators.new(user_params)
    if @pupil.save
      redirect_to [:admin, :pupils]
    else
      render :new
    end
  end

  def update
    if @pupil.update(user_params)
      redirect_to [:edit, :admin, @pupil]
    else
      render :edit
    end
  end

  def index
    @pupils = User::Pupil.all
  end

  private

    def set_pupil
      @pupil = User::Pupil.find(params[:id])
    end

    def user_params
      params.require(:user_faculty).permit(:name, :email, :password, :password_confirmation, :school_id)
    end

end

app/controllers/faculties/pupils_controller.rb
class Faculties::PupilsController < FacultyController
  before_action :verify_administrator, only: [:new, :create, :edit, :update, :destroy, :add_to_class, :leave_class]
  before_action :set_pupil, only: [:show, :update, :edit, :add_to_class, :leave_class, :destroy, :graph_json]

  def show
  end

  def edit
  end

  def index
    pupil_driver = signed_in_as_administrator? ? @school : current_user
    @q = pupil_driver.pupils.ransack(params[:q])
    @pupils = @q.result(distinct: true)
  end

  def new
    @pupil = @school.pupils.build
  end

  def create
    @pupil = @school.pupils.build(pupil_params)
    if @pupil.save
      unless params[:user_pupil][:klass].blank?
        @pupil.enroll_in Klass.find(params[:user_pupil][:klass])
      end
      flash[:notice] = 'Pupil created'
      @school.notify("#{view_context.link_to(@pupil.name, faculty_pupil_path(@pupil))} has been added as a new #{view_context.link_to('pupil', faculty_pupils_path)}")
      redirect_to faculty_pupil_path(@pupil)
    else
      render :new
    end
  end

  def update
    if @pupil.update(pupil_params)
      unless params[:user_pupil][:klass].blank?
        @pupil.enroll_in Klass.find(params[:user_pupil][:klass])
      end
      flash[:notice] = 'Pupil updated'
      @school.notify("#{view_context.link_to(@pupil.name, faculty_pupil_path(@pupil))} has been updated")
      redirect_to faculty_pupil_path(@pupil)
    else
      render :edit
    end
  end

  def add_to_class
    klass = Klass.find(params[:klass_id])
    @pupil.enroll_in(klass)
    redirect_to edit_faculty_klass_path(klass, tab: 'manage')
  end

  def leave_class
    klass = Klass.find(params[:klass_id])
    @pupil.leave(klass)
    redirect_to edit_faculty_klass_path(klass, tab: 'manage')
  end

  def import
    file = params[:csv_file]
    unless File.extname(file.original_filename) == ".csv"
      flash[:error] = "File format is not supported"
      return redirect_to faculty_pupils_url
    end
    begin
      User::Pupil.import_csv(@school, file)
    rescue => e
      flash[:error] = e.message
    else
      flash[:success] = "Pupils Imported"
    ensure
      redirect_to faculty_pupils_url
    end
  end

  def destroy
    @pupil.destroy
    redirect_to faculty_pupils_path
  end

  def graph_json
    respond_to do |format|
      format.json {render "faculty/pupils/graphs/#{params[:chart_type]}"}
    end
  end


  private

    def set_pupil
      @pupil = User.friendly.find(params[:id])
    end

    def pupil_params
      params.require(:user_pupil).permit(:name, :email, :age, :gender, :pupil_identifier, :dob, :study_year_id, :klass, :specified_class)
    end

    def verify_administrator
      redirect_to faculty_root_path unless signed_in_as_administrator?
    end


end

app/controllers/pupil/achievements_controller.rb
class Pupil::AchievementsController < PupilController

  def index
    @avatars = Avatar.all_for current_user
  end

  def set_avatar
    current_user.update(avatar: current_user.avatars.find(params[:id]))
    redirect_to pupil_root_path
  end


end

app/controllers/pupil/lessons_controller.rb
class Pupil::LessonsController < PupilController
  skip_before_action :send_demo_to_library, only: [:library, :big_preview]

  def index
    @results = current_user.lesson_results
  end

  def show
    if params[:fun]
      @result = current_user.q_fun_quiz_attempt
      @fun = true
    else
      @result = current_user.lessons.find(params[:id]).get_result_for current_user
    end
  end

  def big_preview
    @lesson = Lesson.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def library
    @lessons = @pupil.lessons
  end


end

app/controllers/pupil/pupil_controller.rb
class Pupil::PupilController < PupilController


  def home
    @lesson = current_user.courses.first&.lessons&.active
  end

  def library
  end

  def set_avatar
    current_user.update(avatar: current_user.avatars.find(params[:avatar_id]))
    redirect_to pupil_root_path
  end

  def charts
    @pupil = current_user
    respond_to do |format|
      format.json {render "pupil/charts/#{params[:chart_type]}"}
    end
  end

  def my_class
    @pupils = @pupil.klasses.first.pupils.sort { |pupil| pupil.lesson_results.sum(&:total) }.reverse
  end

end

app/controllers/pupil/quizzes_controller.rb
class Pupil::QuizzesController < PupilController
  layout 'presentation'

  before_action :set_lesson
  before_action :set_attempt
  before_action :confirm_started, except: :start_quiz

  def start_quiz
    if @completed
      @attempt.fun_start!
    else
      @attempt.start!
    end
    redirect_to question_pupil_lesson_path(@lesson)
  end

  def question
    unless @question = @attempt.questions.current
      if @completed
        current_user.update(fun_quiz_lesson_id: nil)
        redirect_to pupil_lesson_path(@lesson, fun: true)
      else
        @attempt.finish!
        redirect_to pupil_lesson_path(@lesson)
      end
    end
  end

  def submit_answer
    current_question = @attempt.questions.current
    #questions numbers match
    #they could be caused to mismatch by opening the quiz in multiple tabs
    #thus you could progress on one screen (advanving the current question)
    #then submit a second answer on the other
    if current_question && current_question.question_number.to_s == params[:question_number]
      current_question.update(answer_id: params[:answer_id])
      if current_question.incorrect?
        @slide = current_question.slide
        @presentation = @slide.presentation
        @slides = @presentation.student_slides
        @questions = @attempt.questions
        @question = current_question
        render 'presentations/show'
      else

        redirect_to question_pupil_lesson_path(@lesson)
      end
    else
      redirect_to question_pupil_lesson_path(@lesson)
    end
  end



  private

    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def set_attempt
      lesson_result = @lesson.get_result_for current_user
      @attempt = lesson_result.attempt

      if @attempt.completed?
        @completed = true
        @attempt = current_user.fun_quiz_attempt(@lesson)
      end
    end

    def confirm_started
      unless @attempt.started?
        start_quiz
      end
    end

end

app/controllers/pupil/results_controller.rb
class Pupils::ResultsController < ApplicationController

  def index
    @results = current_user.lesson_results
  end

  def show
    @attempt = current_user.lesson_results.find(params[:id]).attempt
  end

end

app/controllers/pupil_controller.rb
class PupilController < ApplicationController

  layout 'pupil_application'

  before_action :set_school
  before_action :require_pupil
  before_action :send_demo_to_library

  private

  def set_school
    @school = School.find_by(subdomain: current_subdomain)
  end

  def require_pupil
    if signed_in? && current_user.pupil?
      @pupil = current_user
    else
      flash[:error] = "You do not have permission to access that page. Please sign in to continue"
      redirect_to login_path
    end
  end

  def send_demo_to_library
    if @pupil.demo
      redirect_to pupil_my_library_path
    end
  end

end

app/helpers/pupil_helper.rb
module PupilHelper


  def pupil_mission_thumbnail mission
    content_tag :div, class: 'pupil_mission_thumbnail_container', data: {mid: mission.machine_name} do
      content_tag :div, class: 'pupil_mission_thumbnail' do
        link_to(image_tag(mission.cover_image.pupil_thumbnail), pupil_mission_path(mission), remote: true)
      end
    end
  end

  def greeting
    now = Time.now
    today = Date.today.to_time

    morning = today.beginning_of_day
    noon = today.noon
    evening = today.change( hour: 17 )
    night = today.change( hour: 20 )
    tomorrow = today.tomorrow

    message = case now
    when morning..noon
      'Good Morning'
    when noon..evening
      'Good Afternoon'
    when evening..night
      'Good Evening'
    when night..tomorrow
      'Good Night'
    end
  end

end

app/helpers/pupils/results_helper.rb
module Pupils::ResultsHelper
end

app/views/pupil/pupil/_pupil_mission_thumbnail.html.haml
.pupil_mission_thumbnail_container{data: {mid: lesson.machine_name}}
  .pupil_mission_thumbnail{class: ('disabled' unless lesson.available?)}
    - if lesson.available?
      = link_to(image_tag(lesson.cover_image.pupil_thumbnail), big_preview_pupil_lesson_path(lesson), remote: true)
    - else
      = image_tag(lesson.cover_image.pupil_thumbnail)

app/views/pupil/pupil/_welcome.html.haml
#welcome_container
  #welcome_container_inner
    #school_info
      = image_tag @school.display_logo
      %h2= @school.name
    #profile
      #profile_picture
        = image_tag current_user.avatar_image
      #profile_content
        %h4= "#{greeting}, #{current_user.name}!"
        #profile_trophys
          .trophy= image_tag('http://www.seaicons.com/wp-content/uploads/2016/05/Trophy-bronze-icon.png', title: 'bronze trophy')
          .trophy= image_tag('http://www.seaicons.com/wp-content/uploads/2016/05/Trophy-silver-icon.png', title: 'silver trophy')
          .trophy= image_tag('http://www.seaicons.com/wp-content/uploads/2016/05/Trophy-gold-icon.png', title: 'gold trophy')
        #profile_progress
          .progress_bar_container{data: {total_progress: @pupil.lessons.count}}
            .progress_bar.lesson_progress_bar{data: {progress: @pupil.lessons.available.count}}
            .progress_bar.task_progress_bar{data: {progress: @pupil.lessons.count - @pupil.lessons.available.count}}
          .milestones
            %span{style: 'color: green'}
              = pluralize @pupil.lessons.available.count, 'mission'
              completed
            %span{style: 'color: #FF9800'}
              = pluralize @pupil.lessons.count - @pupil.lessons.available.count, 'mission'
              to go
            %span
              = pluralize @pupil.lesson_results.to_a.count{|x| !x.attempt.completed?}, 'task'
              available

  #pupil_welcome_graph.welcome_graph{data: {chart_url: pupil_path(:performance, format: :json)}}

app/views/pupil/pupil/home.html.haml
= render 'welcome'

#lesson_show_panel_container.entrance
- if @lesson
  #this_weeks_lesson
    .pupil_mission_thumbnail_container.large{data: {mid: @lesson.machine_name}, style: "background-image: url(#{image_path(@lesson.cover_image)})"}
    #mission_preview
      .mission_preview_summary_container
        %h1 This week's mission:
        %h2
          Mission Objective
          %br
          #{@presentation&.lesson_template&.study_year&.mascot_name} wants you to:
        %h3= "- #{@lesson.name}"

        %p
          %b Rocket Words:
          %br
          = @lesson.rocket_words.map{ |w| content_tag(:span, w.word, class: 'rw') }.join(', ').html_safe

        = link_to 'Watch Presentation', course_presentation_slide_path(@lesson.course, @lesson.presentation, @lesson.presentation.slides.first), class: 'begin_mission'
        - if @lesson.get_result_for(current_user).attempt.completed?
          = link_to 'Quiz Completed', pupil_lesson_path(@lesson), class: 'begin_mission'
          = link_to 'Try again for fun?', start_quiz_pupil_lesson_path(@lesson), class: 'begin_mission'
        - else
          = link_to 'Take Quiz', start_quiz_pupil_lesson_path(@lesson), class: 'begin_mission'

#pupil_mission_list
  = render partial: 'pupil/lessons/pupil_lesson_thumbnail', collection: @pupil.lessons, as: :lesson

app/views/pupil/pupil/my_class.html.haml
%table.pupil_table
  %thead
    %tr
      %th Name
      %th Quizzes Completed
      %th Score
  %tbody
    - @pupils.each do |pupil|
      %tr
        %td
          - if pupil == current_user
            = pupil.name
          - else
            = '*' * 4
            = '*' * 4
        %td= pupil.lesson_results.count
        //%td= pupil.lesson_results.sum(&:total)